CREATE TABLE "token_analyses" (
	"id" serial PRIMARY KEY NOT NULL,
	"token_id" text NOT NULL,
	"token_symbol" text NOT NULL,
	"token_name" text NOT NULL,
	"token_image" text,
	"chain" text,
	"contract_address" text,
	"final_score" numeric(6, 2) NOT NULL,
	"tier" text NOT NULL,
	"phase" integer,
	"phase_name" text,
	"narrative" text,
	"narrative_heat" numeric(4, 1),
	"narrative_acceleration" text,
	"peak_proximity" numeric(5, 2),
	"winning_side" text,
	"consensus_level" text,
	"confidence" text,
	"coordination_score" numeric(5, 2),
	"schelling_rank_score" numeric(5, 2),
	"schelling_position" text,
	"reflexivity_score" numeric(5, 2),
	"virality_score" numeric(5, 2),
	"asymmetry_score" numeric(5, 2),
	"asymmetry_floor" text,
	"asymmetry_ceiling" text,
	"game_theory_bonus" numeric(5, 2),
	"phase_modifier" numeric(5, 2),
	"narrative_modifier" numeric(5, 2),
	"exit_liquidity_modifier" numeric(5, 2),
	"peak_proximity_modifier" numeric(5, 2),
	"data_quality_modifier" numeric(5, 2),
	"equilibrium_type" text,
	"equilibrium_evolution" text,
	"player_map" text,
	"dominant_strategies" text,
	"coordination_risks" jsonb,
	"catalysts" jsonb,
	"recommendation" text,
	"display_summary" text,
	"verdict" text,
	"reasoning" text,
	"model_scores" jsonb,
	"current_price" numeric(20, 10),
	"market_cap" numeric(20, 2),
	"fdv" numeric(20, 2),
	"volume_24h" numeric(20, 2),
	"price_change_24h" numeric(10, 4),
	"price_change_7d" numeric(10, 4),
	"categories" jsonb,
	"status" text DEFAULT 'pending' NOT NULL,
	"gumloop_run_id" text,
	"raw_gumloop_response" text,
	"user_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
